// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADaXwsg138m_3covnC-vbIIgYI0BCOV4M',
    appId: '1:40540803887:web:71757f60067cd6bce387da',
    messagingSenderId: '40540803887',
    projectId: 'chatapp-d135c',
    authDomain: 'chatapp-d135c.firebaseapp.com',
    storageBucket: 'chatapp-d135c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkLeFouoYWDNIAE0Yg7FjiYKESoH4wbrk',
    appId: '1:40540803887:android:ca2ba55f83e1181fe387da',
    messagingSenderId: '40540803887',
    projectId: 'chatapp-d135c',
    storageBucket: 'chatapp-d135c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXNW9B8AmP_bn6mf9xi1bClS20WtHIRA0',
    appId: '1:40540803887:ios:3992cfcd41d9633be387da',
    messagingSenderId: '40540803887',
    projectId: 'chatapp-d135c',
    storageBucket: 'chatapp-d135c.appspot.com',
    iosBundleId: 'com.example.logintoac',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXNW9B8AmP_bn6mf9xi1bClS20WtHIRA0',
    appId: '1:40540803887:ios:980ffc7bc8a58409e387da',
    messagingSenderId: '40540803887',
    projectId: 'chatapp-d135c',
    storageBucket: 'chatapp-d135c.appspot.com',
    iosBundleId: 'com.example.logintoac.RunnerTests',
  );
}
